require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  # 3017, not Rails' default 3000 — see config/puma.rb. A link generated here
  # pointing at 3000 would open a different application running on this box.
  config.action_mailer.default_url_options = { host: "localhost", port: 3017 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # ── AND ANSWER IT IN JSON, BECAUSE THIS IS AN api_only APP ────────────────
  #
  # `migration_error` above renders Rails' own HTML error page, which is right
  # for a browser and unreadable to every client this app actually has. A
  # migration left unapplied here once put the public endpoints on 500 for
  # every session on this box and the symptom named nothing —
  # `check_pending_migrations` refuses even the pre-auth routes, so from
  # another session it reads as "the API is down".
  #
  # DEVELOPMENT ONLY, and not by oversight: `CheckPending` is only in the stack
  # when `migration_error` is set, which is here. Production migrates as a
  # deploy step and this middleware is not inserted there at all — so nothing
  # in production returns this 503, and `insert_before` would raise at boot if
  # this were moved to a shared config.
  #
  # `require`d rather than autoloaded: the stack is built during boot, where
  # autoloading is not supported, which is why `lib/middleware` is on
  # `autoload_lib`'s ignore list in config/application.rb.
  require Rails.root.join("lib/middleware/pending_migration_json")
  config.middleware.insert_before ActiveRecord::Migration::CheckPending,
                                  PendingMigrationJson

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
